# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDir: '$(Build.SourcesDirectory)/env/dev'

stages:
# =========================
# PLAN STAGE
# =========================
- stage: TerraformPlan
  displayName: Terraform Plan
  jobs:
  - job: plan
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformWorkingDir)'
        backendServiceArm: 'azuredevops-serviceconnection'
        backendAzureRmResourceGroupName: 'RG'
        backendAzureRmStorageAccountName: 'storageacc316'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(terraformWorkingDir)'
        environmentServiceNameAzureRM: 'azuredevops-serviceconnection'
        commandOptions: '-lock=false -input=false tfplan'

    - task: PublishPipelineArtifact@1
      displayName: Publish tfplan
      inputs:
        targetPath: '$(terraformWorkingDir)/tfplan'
        artifact: tfplan

# =========================
# APPLY STAGE
# =========================
- stage: TerraformApply
  displayName: Terraform Apply
  dependsOn: TerraformPlan
  condition: succeeded()
  jobs:
  - job: apply
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformWorkingDir)'
        backendServiceArm: 'azuredevops-serviceconnection'
        backendAzureRmResourceGroupName: 'RG'
        backendAzureRmStorageAccountName: 'storageacc316'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

    - task: DownloadPipelineArtifact@2
      displayName: Download tfplan
      inputs:
        artifact: tfplan
        path: '$(terraformWorkingDir)'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(terraformWorkingDir)'
        environmentServiceNameAzureRM: 'azuredevops-serviceconnection'
        commandOptions: 'tfplan'